export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const CANCEL_FRIEND_REQUEST = "CANCEL_FRIEND_REQUEST";
export const REMOVE_FRIEND = "REMOVE_FRIEND";

export const UPDATE_CONVERSATION = "UPDATE_CONVERSATION";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
